# Site settings
title: 2zki's blog # 你的博客名字，可以定义修订
header-img: "img/green.jpg"
tagline: "2zki"  
description: "This is 2zki's blog."  # 一句话描述你的博客
baseurl: "http://2zkiw.github.io"
url: "http://2zkiw.github.io"  # 此处填写你的博客地址 

# About/contact
owner: 
  name: "2zki" # 填写作者信息：名字
  email: 2zki333@gmail.com # 填写作者信息：邮箱
  bio: "This is 2zki's blog." # 填写作者信息：博客描述

# Data
gavatar: img/green.jpg # 浏览器地址栏小图标，可自定义更改
favicon: img/green.jpg # 浏览器地址栏小图标，可自定义更改

douban_username:  # 你的豆瓣id
twitter_username: 
github_username: 
facebook_username: 
weibo_username: 
zhihu_username: 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/Toronto

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "2zki" # 你的名字
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus # 使用 disqus 评论模块，读者翻墙才能看见
  duoshuo :
    short_name :  # 填写你的 disqus id
  disqus :
      short_name :  # 填写你的 disqus id

# Analytics and webmaster tools stuff goes here
google_analytics:  # 填写你  google_analytics id
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
